### ISSUE TITLE
data TF peaks h5 file

### ISSUE THREAD

**Issue by sandraleebatista** [fransilvion/ExplaiNN#1]
Hello for the demo code on the readme page, is the correct h5 file in the data directory as tf_peaks_TEST_sparse_Remap.h5?

Thanks, Sandra

**Comment by fransilvion** [comment]
Hi Sandra,

Yes, this is the correct file

**Comment by sandraleebatista** [comment]
Thanks. Can you please share link to more information on setting up our own data to use ExplaiNN? I could not get that file to work when I tried the  code on readme, but will give it another try now. I would like to use on our own data, but not sure from documentation yet how to prepare it. Thanks again, Sandra

**Comment by fransilvion** [comment]
Sandra, could you please try to download and run the code on this file?

https://drive.google.com/drive/folders/1tFWWTCUoE2Jg0zrMvKKtTqEBuwkkJ1bl?usp=sharing

Also make sure that you have h5py library installed.

As for the how to process your data for ExplaiNN, it is really the same as for any other network, when you prepare DataLoader in pytorch. You need an array of one-hot encoded sequences and an array with desired outputs. For the simple illustration consider this example of the data from AI-TAC paper:

```python
x = np.load("../../AI-TAC/ai_tac_data/one_hot_seqs.npy")
x = x.astype(np.float32)
y = np.load("../../AI-TAC/ai_tac_data/cell_type_array.npy")
y = y.astype(np.float32)
peak_names = np.load("../../AI-TAC/ai_tac_data/peak_names.npy")

train_data, eval_data, train_labels, eval_labels, train_names, eval_names = train_test_split(x, y,
                                                                                             peak_names,
                                                                                             test_size=0.1, 
                                                                                             random_state=40)


train_dataset = torch.utils.data.TensorDataset(torch.from_numpy(train_data), torch.from_numpy(train_labels))
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

eval_dataset = torch.utils.data.TensorDataset(torch.from_numpy(eval_data), torch.from_numpy(eval_labels))
eval_loader = torch.utils.data.DataLoader(dataset=eval_dataset, batch_size=batch_size, shuffle=True)
```

These files can be also downloaded from the above link. 

As for the h5 file, I just noticed that it's a nice way to prepare/load your data, I was basically using this code:
```python
from explainn import utils

#assuming that training sequences is a pandas Series with strings (DNA sequences)
train_sequences = train_sequences.map(lambda x: utils.dna_one_hot(x, flatten=False))
train_sequences = np.stack(train_sequences, axis=0)

valid_sequences = valid_sequences.map(lambda x: utils.dna_one_hot(x, flatten=False))
valid_sequences = np.stack(valid_sequences, axis=0)

test_sequences = test_sequences.map(lambda x: utils.dna_one_hot(x, flatten=False))
test_sequences = np.stack(test_sequences, axis=0)
print("Done encoding the data")

# train_peaks etc have the output variable per sequence, these are your Ys

Output_h5 = "dataset.h5"
h5f = h5py.File(Output_h5, 'w')

#target labels is the list of your output classes
h5f.create_dataset('target_labels', data=target_labels)

h5f.create_dataset('train_in', data=train_sequences)
h5f.create_dataset('train_out', data=train_peaks)

h5f.create_dataset('valid_in', data=valid_sequences)
h5f.create_dataset('valid_out', data=valid_peaks)

h5f.create_dataset('test_in', data=test_sequences)
h5f.create_dataset('test_out', data=test_peaks)

h5f.close()
```

And now you can use this dataset later in your experiments. For example, you can load it easily with utils.load_datas. Let me know if smth doesn't work, or if you have other questions

**Comment by sandraleebatista** [comment]
Thanks will give it a try a little later this morning. It is definitely the h5 file. I think the h5py is correct installed. Here are the errors I am getting if helpful:
ile ".../python3.10/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)



When I try to get file using git-lfs: 
(git-lfs checkout
Skipped checkout for "data/tf_peaks_TEST_sparse_Remap.h5", content not local. Use fetch to download.
Checking out LFS objects: 100% (5/5), 155 MB | 0 B/s, done.
 git-lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/wassermanlab/ExplaiNN.git/info/lfs'

**Comment by fransilvion** [comment]
I see, can you please try the same with the h5 file from the google drive I shared?

**Comment by sandraleebatista** [comment]
Thanks, the files in the drive worked. 

For training the model, how should criterion, optimizer, and weights_folder be set? Tutorial as written on readme do not have these set. Thanks again/

**Comment by fransilvion** [comment]
Just updated the Readme file, now it has the info about optimizer, weight_folder, and criterion (loss function).
